<?php

// require other translation files
include_once framework::resolve("packages/base/i18n/en/forms.php");

// page description
$i18n['title'] = 'My profile';

// personal information
$i18n['info-header'] = 'Personal information';
$i18n['info-help'] = 'Your personal information help us to tailor the way we connect with you, to select the notifications and news you are more likely to enjoy from our mailing list and to prepopulate areas in our website in order to make your life easier. This information will be only visible to you and will <strong>never</strong> be shared, sold, or rented';
$i18n['info-full-name'] = 'Your name';

// address
$i18n['address-header'] = 'Your address';
$i18n['address-help'] = 'Your address is used to calculate distances and to prepopulate areas inside our website, in order to make your life easier. We are sorry to say that only address inside the United States are allowed, since we cannot deliver to foreign countries yet. Please insert your full address, including zipcode, in the way the mail service can understand it properly.';

// change password
$i18n['chnpass-header'] = 'Change password';
$i18n['chnpass-oldpass'] = 'Current password';
$i18n['chnpass-newpass'] = 'New password';
$i18n['chnpass-newpass-title'] = 'Six or more characters';
$i18n['chnpass-repeatpass'] = 'Repeat password';
$i18n['chnpass-help'] = 'Changing your password periodically, and choosing a password with more than eight characters (including numbers and caps) is the best way to avoid hackers and keep your information save. Also, please update as soon as possible the autogenerated password that you received to your email when your account was created or reseted.';

// buttons
$i18n['btn-saveprofile'] = 'Save profile';

