<?php
	// page description
	$i18n['title'] = 'Store';

	// items
	$i18n['item-header'] = 'Pick an item';
	$i18n['item-msg'] = '<strong>Your item was selected!</strong> Now go and choose the wrapping paper that pleases your heart. If you want another item instead, remove from the shopping cart the one you just picked and the list will appear again.';
	$i18n['item-add-cart'] = 'Add';
	$i18n['item-see-more'] = 'More';

	// cards
	$i18n['card-header'] = 'Add a card';
	$i18n['card-config-msg1'] = '<strong>You selected a card, now you just need to configure it.</strong> Add the message that will be displayed on the card. Not very inspired now? Don\'t worry, just pick one from our long selection of messages. Select the category and click refresh until you got the one you like. If you want to use another card instead, just';
	$i18n['card-config-msg2'] = 'click here to show the cards again';
	$i18n['card-msg'] = '<strong>You added a card.</strong> The card is now in your shopping cart. If you want to select another card instead, remove from the shopping cart the one you just picked and the list will appear again.';
	$i18n['card-error-blank'] = '<strong>You need to add some text to your card!</strong> C\'mon, don\'t be that lazy. Use one of the autogenerated text on this page, but never send a card in black.';
	$i18n['card-warning-msg'] = '<span class="orange">Warning:</span> Message will be printed exactly as it was typed. Please double check for typos';
	$i18n['printed'] = 'Printed';
	$i18n['handwritten'] = 'Handwritten';
	$i18n['btn-add-card'] = 'Add to shopping cart';

	// wrapping paper
	$i18n['wrap-header'] = 'Wrap your gift';
	$i18n['wrap-msg'] = '<strong>The wrapping paper was selected!</strong> If you already selected an item, you can now jump to the next step, where you will send the present. If you want another wrapping paper instead, remove from the shopping cart the one you just picked and the list will appear again.';

	// bags
	$i18n['bag-header'] = 'Add a bag';
	$i18n['bag-msg'] = '<strong>You selected a gift bag.</strong> Your present is looking every time more beautiful, now it will be perfect to add some ornamentation. If you want another gift bag paper instead, just remove from the shopping cart the one you picked and the list will appear again.';

	// ornaments
	$i18n['ornament-header'] = 'Add ornaments';
	$i18n['ornament-header-each'] = 'each';
	$i18n['ornament-depleted'] = '<strong>WOW you have picked all the ornaments from our list.</strong> I can see you are a person who takes presence seriously. Unfortunately we have no more ornaments to offer now, but we recorded this event to add more ornaments shortly.';
	$i18n['ornament-label-counter'] = 'added so far';
	$i18n['add'] = 'Add';

	// general
	$i18n['product-remove'] = "Remove from cart";
	$i18n['label-optional'] = 'optional';
	$i18n['label-done'] = 'done!';
	$i18n['btn-pick'] = 'Pick';
?>